// src/services/mockData.js

export const mockIPOData = {
  
    
    "upcoming": [
      {
        "symbol": "BEEZAASAN",
        "name": "Beezaasan Explotech Limited",
        "status": "upcoming",
        "is_sme": true,
        "additional_text": "Bid starts on 21 Feb at 10 AM",
        "min_price": 165,
        "max_price": 175,
        "issue_price": null,
        "listing_gains": null,
        "listing_price": null,
        "bidding_start_date": "2025-02-21",
        "bidding_end_date": null,
        "listing_date": "2025-03-03",
        "lot_size": null,
        "document_url": "https://www.bsesme.com/download/323425/DRHPBeezaasanExplotechLimited_20241130223137.pdf"
      },
      {
        "symbol": "FABINDIA",
        "name": "FabIndia",
        "status": "upcoming",
        "is_sme": false,
        "additional_text": "Bidding dates yet to be announced",
        "min_price": null,
        "max_price": null,
        "issue_price": null,
        "listing_gains": null,
        "listing_price": null,
        "bidding_start_date": null,
        "bidding_end_date": null,
        "listing_date": null,
        "lot_size": null,
        "document_url": "https://www.sebi.gov.in/filings/public-issues/jan-2022/fabindia-limited_55532.html"
      },
      {
        "symbol": "OYO",
        "name": "OYO",
        "status": "upcoming",
        "is_sme": false,
        "additional_text": "Bidding dates yet to be announced",
        "min_price": null,
        "max_price": null,
        "issue_price": null,
        "listing_gains": null,
        "listing_price": null,
        "bidding_start_date": null,
        "bidding_end_date": null,
        "listing_date": null,
        "lot_size": null,
        "document_url": "https://www.sebi.gov.in/filings/public-issues/oct-2021/oravel-stays-limited_53084.html"
      },
      {
        "symbol": "BOAT",
        "name": "boAt ",
        "status": "upcoming",
        "is_sme": false,
        "additional_text": "Bidding dates yet to be announced",
        "min_price": null,
        "max_price": null,
        "issue_price": null,
        "listing_gains": null,
        "listing_price": null,
        "bidding_start_date": null,
        "bidding_end_date": null,
        "listing_date": null,
        "lot_size": null,
        "document_url": "https://www.sebi.gov.in/filings/public-issues/jan-2022/imagine-marketing-limited_55666.html"
      },
      {
        "symbol": "BAJAJENER",
        "name": "Bajaj Energy",
        "status": "upcoming",
        "is_sme": false,
        "additional_text": "Bidding dates yet to be announced",
        "min_price": null,
        "max_price": null,
        "issue_price": null,
        "listing_gains": null,
        "listing_price": null,
        "bidding_start_date": null,
        "bidding_end_date": null,
        "listing_date": null,
        "lot_size": null,
        "document_url": "https://www.sebi.gov.in/filings/public-issues/apr-2019/bajaj-energy-limited_42638.html"
      },
      {
        "symbol": "STUDDS",
        "name": "Studds Accessories",
        "status": "upcoming",
        "is_sme": false,
        "additional_text": "Bidding dates yet to be announced",
        "min_price": null,
        "max_price": null,
        "issue_price": null,
        "listing_gains": null,
        "listing_price": null,
        "bidding_start_date": null,
        "bidding_end_date": null,
        "listing_date": null,
        "lot_size": null,
        "document_url": "https://www.sebi.gov.in/filings/public-issues/aug-2018/studds-accessories-limited_40127.html"
      },
      {
        "symbol": "AROHAN",
        "name": "Arohan Financial",
        "status": "upcoming",
        "is_sme": false,
        "additional_text": "Bidding dates yet to be announced",
        "min_price": null,
        "max_price": null,
        "issue_price": null,
        "listing_gains": null,
        "listing_price": null,
        "bidding_start_date": null,
        "bidding_end_date": null,
        "listing_date": null,
        "lot_size": null,
        "document_url": "https://www.sebi.gov.in/filings/public-issues/feb-2021/arohan-financial-services-limited_49148.html"
      },
      {
        "symbol": "SNAPDEAL",
        "name": "Snapdeal",
        "status": "upcoming",
        "is_sme": false,
        "additional_text": "Bidding dates yet to be announced",
        "min_price": null,
        "max_price": null,
        "issue_price": null,
        "listing_gains": null,
        "listing_price": null,
        "bidding_start_date": null,
        "bidding_end_date": null,
        "listing_date": null,
        "lot_size": null,
        "document_url": "https://www.sebi.gov.in/sebi_data/attachdocs/dec-2021/1640066533522.pdf"
      },
      {
        "symbol": "DROOM",
        "name": "Droom",
        "status": "upcoming",
        "is_sme": false,
        "additional_text": "Bidding dates yet to be announced",
        "min_price": null,
        "max_price": null,
        "issue_price": null,
        "listing_gains": null,
        "listing_price": null,
        "bidding_start_date": null,
        "bidding_end_date": null,
        "listing_date": null,
        "lot_size": null,
        "document_url": "https://www.sebi.gov.in/filings/public-issues/nov-2021/droom-technology-limited_53946.html"
      },
      {
        "symbol": "SOLAR91CLEANTECH",
        "name": "Solar91 Cleantech",
        "status": "upcoming",
        "is_sme": true,
        "additional_text": "Bidding dates yet to be announced",
        "min_price": 185,
        "max_price": 195,
        "issue_price": null,
        "listing_gains": null,
        "listing_price": null,
        "bidding_start_date": null,
        "bidding_end_date": null,
        "listing_date": "2025-01-01",
        "lot_size": null,
        "document_url": "https://www.solar91.com/investor/investor-files/RHP_Solar91_new.pdf"
      },
      {
        "symbol": "ZEP123",
        "name": "Zepto",
        "status": "upcoming",
        "is_sme": false,
        "additional_text": "Bidding dates yet to be announced",
        "min_price": null,
        "max_price": null,
        "issue_price": null,
        "listing_gains": null,
        "listing_price": null,
        "bidding_start_date": null,
        "bidding_end_date": null,
        "listing_date": null,
        "lot_size": null,
        "document_url": null
      }
    ],
    "listed": [
      {
        "symbol": "CHANDAN",
        "name": "Chandan Healthcare Limited",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 165.1 for 3.84% gains",
        "min_price": 151,
        "max_price": 159,
        "issue_price": 159,
        "listing_gains": 3.83647798742138,
        "listing_price": 165.1,
        "bidding_start_date": "2025-02-10",
        "bidding_end_date": null,
        "listing_date": "2025-02-17",
        "lot_size": null,
        "document_url": "https://nsearchives.nseindia.com/emerge/corporates/content/Registration_29092024183445_DRHP.pdf"
      },
      {
        "symbol": "AJAXENGG",
        "name": "Ajax Engineering",
        "status": "listed",
        "is_sme": false,
        "additional_text": "Listed at 576.0 for 8.43% loss",
        "min_price": 599,
        "max_price": 629,
        "issue_price": 629,
        "listing_gains": -8.426073131955485,
        "listing_price": 576,
        "bidding_start_date": "2025-02-10",
        "bidding_end_date": null,
        "listing_date": "2025-02-17",
        "lot_size": null,
        "document_url": "https://cdn.prod.website-files.com/65006e6ed741800ddeb94c08/67a262ce602b0328aaa3c93d_Red%20Herring%20Prospectus%20(RHP).pdf"
      },
      {
        "symbol": "ELGNZ",
        "name": "Eleganz Interiors",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 122.0 for 6.15% loss",
        "min_price": 123,
        "max_price": 130,
        "issue_price": 130,
        "listing_gains": -6.153846153846154,
        "listing_price": 122,
        "bidding_start_date": "2025-02-07",
        "bidding_end_date": null,
        "listing_date": "2025-02-14",
        "lot_size": null,
        "document_url": "https://nsearchives.nseindia.com/emerge/corporates/content/EleganzInteriorsLimited_RHP.pdf"
      },
      {
        "symbol": "SOLARIUM",
        "name": "Solarium Green Energy",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 202.0 for 5.76% gains",
        "min_price": 181,
        "max_price": 191,
        "issue_price": 191,
        "listing_gains": 5.7591623036649215,
        "listing_price": 202,
        "bidding_start_date": "2025-02-06",
        "bidding_end_date": null,
        "listing_date": "2025-02-13",
        "lot_size": null,
        "document_url": "https://solariumenergy.in/wp-content/uploads/2025/02/RHP_SolariumGreenEnergy-BSE.pdf"
      },
      {
        "symbol": "READYMIX",
        "name": "Readymix Construction Machinery",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 123.0 for 0.00% gains",
        "min_price": 121,
        "max_price": 123,
        "issue_price": 123,
        "listing_gains": 0,
        "listing_price": 123,
        "bidding_start_date": "2025-02-06",
        "bidding_end_date": null,
        "listing_date": "2025-02-13",
        "lot_size": null,
        "document_url": "https://hemadmin.hemsecurities.com/images/Files/offer/708.pdf"
      },
      {
        "symbol": "AMWILL",
        "name": "Amwill Healthcare",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 88.85 for 19.95% loss",
        "min_price": 105,
        "max_price": 111,
        "issue_price": 111,
        "listing_gains": -19.95495495495496,
        "listing_price": 88.85,
        "bidding_start_date": "2025-02-05",
        "bidding_end_date": null,
        "listing_date": "2025-02-12",
        "lot_size": null,
        "document_url": "https://www.amwillhealthcare.com/drhp_investor"
      },
      {
        "symbol": "KEN",
        "name": "Ken Enterprises Limited",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 85.0 for 9.57% loss",
        "min_price": 94,
        "max_price": 94,
        "issue_price": 94,
        "listing_gains": -9.574468085106384,
        "listing_price": 85,
        "bidding_start_date": "2025-02-05",
        "bidding_end_date": null,
        "listing_date": "2025-02-12",
        "lot_size": null,
        "document_url": "https://nsearchives.nseindia.com/emerge/corporates/content/Registration_29092024014927_DP-KEL.pdf"
      },
      {
        "symbol": "CHAMUNDA",
        "name": "Chamunda Electricals Limited",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 70.0 for 40.00% gains",
        "min_price": 47,
        "max_price": 50,
        "issue_price": 50,
        "listing_gains": 40,
        "listing_price": 70,
        "bidding_start_date": "2025-02-04",
        "bidding_end_date": null,
        "listing_date": "2025-02-11",
        "lot_size": null,
        "document_url": "https://www.chamundaconst.com/Content/chamundaconst.com/Document/717Red%20Herring%20Prospectus.pdf"
      },
      {
        "symbol": "AGARWALEYE",
        "name": "Dr Agarwal’s Health Care",
        "status": "listed",
        "is_sme": false,
        "additional_text": "Listed at 402.0 for 0.00% gains",
        "min_price": 382,
        "max_price": 402,
        "issue_price": 402,
        "listing_gains": 0,
        "listing_price": 402,
        "bidding_start_date": "2025-01-29",
        "bidding_end_date": null,
        "listing_date": "2025-02-04",
        "lot_size": null,
        "document_url": "https://investmentbank.kotak.com/downloads/agarwals-healthcare-limited-RHP.pdf"
      },
      {
        "symbol": "MPFL",
        "name": "Malpani Pipes Limited",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 85.9 for 4.56% loss",
        "min_price": 85,
        "max_price": 90,
        "issue_price": 90,
        "listing_gains": -4.555555555555549,
        "listing_price": 85.9,
        "bidding_start_date": "2025-01-29",
        "bidding_end_date": null,
        "listing_date": "2025-02-04",
        "lot_size": null,
        "document_url": "https://www.malpanipipes.com/wp-content/uploads/2025/01/RHP_Malpani_20.01.2025-1.pdf"
      },
      {
        "symbol": "HMEML",
        "name": "HM Electro Mech Limited",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 81.0 for 8.00% gains",
        "min_price": 71,
        "max_price": 75,
        "issue_price": 75,
        "listing_gains": 8,
        "listing_price": 81,
        "bidding_start_date": "2025-01-24",
        "bidding_end_date": null,
        "listing_date": "2025-01-31",
        "lot_size": null,
        "document_url": "https://beelinemb.com/wp-content/uploads/2025/01/RHP-HM.pdf"
      },
      {
        "symbol": "GBLOGISTIC",
        "name": "GB Logistics Commerce",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 81.6 for 20.00% loss",
        "min_price": 95,
        "max_price": 102,
        "issue_price": 102,
        "listing_gains": -20.000000000000007,
        "listing_price": 81.6,
        "bidding_start_date": "2025-01-24",
        "bidding_end_date": null,
        "listing_date": "2025-01-31",
        "lot_size": null,
        "document_url": "https://www.bseindia.com/corporates/download/349132/240308-DRHP-GLCL-Final_20240308004126.pdf"
      },
      {
        "symbol": "CLN",
        "name": "CLN Energy Limited",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 256.0 for 2.40% gains",
        "min_price": 235,
        "max_price": 250,
        "issue_price": 250,
        "listing_gains": 2.4,
        "listing_price": 256,
        "bidding_start_date": "2025-01-23",
        "bidding_end_date": null,
        "listing_date": "2025-01-30",
        "lot_size": null,
        "document_url": "https://www.clnenergy.in/ipo/Offer-Documents/Red%20Herring%20Prospectus%20-CLN.pdf"
      },
      {
        "symbol": "REXPRO",
        "name": "Rexpro Enterprises",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 117.0 for 19.31% loss",
        "min_price": 145,
        "max_price": 145,
        "issue_price": 145,
        "listing_gains": -19.310344827586206,
        "listing_price": 117,
        "bidding_start_date": "2025-01-22",
        "bidding_end_date": null,
        "listing_date": "2025-01-29",
        "lot_size": null,
        "document_url": "https://www.rexpro.co/_files/ugd/53de48_cf6f970d2f0344dbb1a75c31adf7b971.pdf"
      },
      {
        "symbol": "DENTA",
        "name": "Denta Water and Infra Solutions",
        "status": "listed",
        "is_sme": false,
        "additional_text": "Listed at 325.0 for 10.54% gains",
        "min_price": 279,
        "max_price": 294,
        "issue_price": 294,
        "listing_gains": 10.54421768707483,
        "listing_price": 325,
        "bidding_start_date": "2025-01-22",
        "bidding_end_date": null,
        "listing_date": "2025-01-29",
        "lot_size": null,
        "document_url": "https://www.denta.co.in/wp-content/uploads/2025/01/Project-Aqua-RHP-Filing-Versionwithout-declaration-pages.pdf"
      },
      {
        "symbol": "CNINFOTECH",
        "name": "CapitalNumbers Infotech",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 274.0 for 4.18% gains",
        "min_price": 250,
        "max_price": 263,
        "issue_price": 263,
        "listing_gains": 4.182509505703422,
        "listing_price": 274,
        "bidding_start_date": "2025-01-20",
        "bidding_end_date": null,
        "listing_date": "2025-01-27",
        "lot_size": null,
        "document_url": "https://www.capitalnumbers.com/investors-pdf/CapitalNumbers_RHP.pdf"
      },
      {
        "symbol": "EMAIN",
        "name": "EMA Partners",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 156.5 for 26.21% gains",
        "min_price": 117,
        "max_price": 124,
        "issue_price": 124,
        "listing_gains": 26.209677419354836,
        "listing_price": 156.5,
        "bidding_start_date": "2025-01-17",
        "bidding_end_date": null,
        "listing_date": "2025-01-24",
        "lot_size": null,
        "document_url": "https://indorient.in/assets/documents/EMA%20Partners%20India%20Limited_RHP_1736484297.pdf"
      },
      {
        "symbol": "STALLION",
        "name": "Stallion India Fluorochemicals",
        "status": "listed",
        "is_sme": false,
        "additional_text": "Listed at 120.0 for 33.33% gains",
        "min_price": 85,
        "max_price": 90,
        "issue_price": 90,
        "listing_gains": 33.33333333333333,
        "listing_price": 120,
        "bidding_start_date": "2025-01-16",
        "bidding_end_date": null,
        "listing_date": "2025-01-23",
        "lot_size": null,
        "document_url": "https://www.sarthi.in/wp-content/uploads/2025/01/RHP_Stallion.pdf"
      },
      {
        "symbol": "LICL",
        "name": "Landmark Immigration",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 75.0 for 4.17% gains",
        "min_price": 70,
        "max_price": 72,
        "issue_price": 72,
        "listing_gains": 4.166666666666666,
        "listing_price": 75,
        "bidding_start_date": "2025-01-16",
        "bidding_end_date": null,
        "listing_date": "2025-01-23",
        "lot_size": null,
        "document_url": "https://shreni.in/wp-content/uploads/2025/01/RHP_Landmark-Immigration.pdf"
      },
      {
        "symbol": "RIKHAV",
        "name": "Rikhav Securities",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 163.4 for 90.00% gains",
        "min_price": 82,
        "max_price": 86,
        "issue_price": 86,
        "listing_gains": 90,
        "listing_price": 163.4,
        "bidding_start_date": "2025-01-15",
        "bidding_end_date": null,
        "listing_date": "2025-01-22",
        "lot_size": null,
        "document_url": "https://www.rikhav.net/pdf/RHP_Rikhav.pdf"
      },
      {
        "symbol": "KKJEWELS",
        "name": "Kabra Jewels",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 243.2 for 90.00% gains",
        "min_price": 121,
        "max_price": 128,
        "issue_price": 128,
        "listing_gains": 89.99999999999999,
        "listing_price": 243.2,
        "bidding_start_date": "2025-01-15",
        "bidding_end_date": null,
        "listing_date": "2025-01-22",
        "lot_size": null,
        "document_url": "https://ib.marwadichandaranagroup.com/images/investorPdf/RHP.pdf"
      },
      {
        "symbol": "LAXMIDENTL",
        "name": "Laxmi Dental",
        "status": "listed",
        "is_sme": false,
        "additional_text": "Listed at 542.0 for 26.64% gains",
        "min_price": 407,
        "max_price": 428,
        "issue_price": 428,
        "listing_gains": 26.635514018691588,
        "listing_price": 542,
        "bidding_start_date": "2025-01-13",
        "bidding_end_date": null,
        "listing_date": "2025-01-20",
        "lot_size": null,
        "document_url": "https://www.laxmidentallimited.com/public/investors/offer_documents/rhp/Project-Lotus-RHP(withfinancials).pdf"
      },
      {
        "symbol": "BARFLEX",
        "name": "Barflex Polyfilms",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 60.0 for 0.00% gains",
        "min_price": 57,
        "max_price": 60,
        "issue_price": 60,
        "listing_gains": 0,
        "listing_price": 60,
        "bidding_start_date": "2025-01-10",
        "bidding_end_date": null,
        "listing_date": "2025-01-20",
        "lot_size": null,
        "document_url": "https://barflex.co.in/wp-content/uploads/2025/01/BPLRHP30DEC.pdf"
      },
      {
        "symbol": "SATKARTAR",
        "name": "Sat Kartar Shopping",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 153.9 for 90.00% gains",
        "min_price": 77,
        "max_price": 81,
        "issue_price": 81,
        "listing_gains": 90,
        "listing_price": 153.9,
        "bidding_start_date": "2025-01-10",
        "bidding_end_date": null,
        "listing_date": "2025-01-17",
        "lot_size": null,
        "document_url": "https://backendapi.satkartar.co.in/assets/investor/rhp.pdf"
      },
      {
        "symbol": "CAPINVIT",
        "name": "Capital Infra Trust InvIT",
        "status": "listed",
        "is_sme": false,
        "additional_text": "Listed at 99.0 for 1.00% loss",
        "min_price": 99,
        "max_price": 100,
        "issue_price": 100,
        "listing_gains": -1,
        "listing_price": 99,
        "bidding_start_date": "2025-01-07",
        "bidding_end_date": null,
        "listing_date": "2025-01-17",
        "lot_size": null,
        "document_url": "https://capitalinfratrust.com/pdf/Offer-Document.pdf"
      },
      {
        "symbol": "BRGIL",
        "name": "B. R. Goyal Infrastructure",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 135.75 for 0.56% gains",
        "min_price": 128,
        "max_price": 135,
        "issue_price": 135,
        "listing_gains": 0.5555555555555556,
        "listing_price": 135.75,
        "bidding_start_date": "2025-01-07",
        "bidding_end_date": null,
        "listing_date": "2025-01-14",
        "lot_size": null,
        "document_url": "https://beelinemb.com/wp-content/uploads/2025/01/RHP-B.R.Goyal-Infrastructure-Limited.pdf"
      },
      {
        "symbol": "DELTIC",
        "name": "Delta Autocorp",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 175.0 for 34.62% gains",
        "min_price": 123,
        "max_price": 130,
        "issue_price": 130,
        "listing_gains": 34.61538461538461,
        "listing_price": 175,
        "bidding_start_date": "2025-01-07",
        "bidding_end_date": null,
        "listing_date": "2025-01-14",
        "lot_size": null,
        "document_url": "https://www.sebi.gov.in/filings/public-issues/jan-2025/delta-autocorp-limited_90439.html"
      },
      {
        "symbol": "QUADFUTURE",
        "name": "Quadrant Future Tek",
        "status": "listed",
        "is_sme": false,
        "additional_text": "Listed at 370.0 for 27.59% gains",
        "min_price": 275,
        "max_price": 290,
        "issue_price": 290,
        "listing_gains": 27.586206896551722,
        "listing_price": 370,
        "bidding_start_date": "2025-01-07",
        "bidding_end_date": null,
        "listing_date": "2025-01-14",
        "lot_size": null,
        "document_url": "https://quadrantfuturetek.com/pdf/red-herring-prospectus-rhp.pdf"
      },
      {
        "symbol": "AVAX",
        "name": "Avax Apparels and Ornaments",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 133.0 for 90.00% gains",
        "min_price": 70,
        "max_price": 70,
        "issue_price": 70,
        "listing_gains": 90,
        "listing_price": 133,
        "bidding_start_date": "2025-01-07",
        "bidding_end_date": null,
        "listing_date": "2025-01-14",
        "lot_size": null,
        "document_url": "https://avaxapparels.com/wp-content/uploads/2024/09/Prospectus-11-09-2024.pdf"
      },
      {
        "symbol": "INDOBELL",
        "name": "Indobell Insulations",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 87.4 for 90.00% gains",
        "min_price": 46,
        "max_price": 46,
        "issue_price": 46,
        "listing_gains": 90.00000000000001,
        "listing_price": 87.4,
        "bidding_start_date": "2025-01-06",
        "bidding_end_date": null,
        "listing_date": "2025-01-13",
        "lot_size": null,
        "document_url": "https://www.bseindia.com/corporates/download/372520/DP_Indobell_BSE_29082024_20240829230829.pdf"
      },
      {
        "symbol": "SGLTL",
        "name": "Standard Glass Lining",
        "status": "listed",
        "is_sme": false,
        "additional_text": "Listed at 172.0 for 22.86% gains",
        "min_price": 133,
        "max_price": 140,
        "issue_price": 140,
        "listing_gains": 22.857142857142858,
        "listing_price": 172,
        "bidding_start_date": "2025-01-06",
        "bidding_end_date": null,
        "listing_date": "2025-01-13",
        "lot_size": null,
        "document_url": "https://www.sebi.gov.in/filings/public-issues/dec-2024/standard-glass-lining-technology-limited-rhp_90399.html"
      },
      {
        "symbol": "FABCLEAN",
        "name": "Fabtech Technologies",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 161.5 for 90.00% gains",
        "min_price": 80,
        "max_price": 85,
        "issue_price": 85,
        "listing_gains": 90,
        "listing_price": 161.5,
        "bidding_start_date": "2025-01-03",
        "bidding_end_date": null,
        "listing_date": "2025-01-10",
        "lot_size": null,
        "document_url": "https://www.bseindia.com/corporates/download/301133/Fabtech%20Final%20DRHP_20240802234348.pdf"
      },
      {
        "symbol": "PARMESHWAR",
        "name": "Parmeshwar Metal",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 84.5 for 38.52% gains",
        "min_price": 57,
        "max_price": 61,
        "issue_price": 61,
        "listing_gains": 38.52459016393443,
        "listing_price": 84.5,
        "bidding_start_date": "2025-01-02",
        "bidding_end_date": null,
        "listing_date": "2025-01-09",
        "lot_size": null,
        "document_url": "https://www.bsesme.com/download/363659/Parmeshwar_Metal_DRHP_20240630175532.pdf"
      },
      {
        "symbol": "DAVIN",
        "name": "Davin Sons Retail",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 44.0 for 20.00% loss",
        "min_price": 55,
        "max_price": 55,
        "issue_price": 55,
        "listing_gains": -20,
        "listing_price": 44,
        "bidding_start_date": "2025-01-02",
        "bidding_end_date": null,
        "listing_date": "2025-01-09",
        "lot_size": null,
        "document_url": "https://www.navigantcorp.com/images/web-images/pdf/Davin_Prospectus.pdf"
      },
      {
        "symbol": "VANDU",
        "name": "Leo Dry Fruits and Spices",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 68.0 for 30.77% gains",
        "min_price": 51,
        "max_price": 52,
        "issue_price": 52,
        "listing_gains": 30.76923076923077,
        "listing_price": 68,
        "bidding_start_date": "2025-01-01",
        "bidding_end_date": null,
        "listing_date": "2025-01-08",
        "lot_size": null,
        "document_url": "https://shreni.in/wp-content/uploads/2024/12/RHP_-Leo-Dryfruits.pdf"
      },
      {
        "symbol": "TECHNICHEM",
        "name": "Technichem Organics",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 57.25 for 4.09% gains",
        "min_price": 52,
        "max_price": 55,
        "issue_price": 55,
        "listing_gains": 4.090909090909091,
        "listing_price": 57.25,
        "bidding_start_date": "2024-12-31",
        "bidding_end_date": null,
        "listing_date": "2025-01-07",
        "lot_size": null,
        "document_url": "https://shreni.in/wp-content/uploads/2024/12/RHP_Technichem-Organics-Limited.pdf"
      },
      {
        "symbol": "INDOFARM",
        "name": "Indo Farm Equipment",
        "status": "listed",
        "is_sme": false,
        "additional_text": "Listed at 256.0 for 19.07% gains",
        "min_price": 204,
        "max_price": 215,
        "issue_price": 215,
        "listing_gains": 19.069767441860467,
        "listing_price": 256,
        "bidding_start_date": "2024-12-31",
        "bidding_end_date": null,
        "listing_date": "2025-01-07",
        "lot_size": null,
        "document_url": "https://nsearchives.nseindia.com/corporate/Indo_DRHP.pdf"
      },
      {
        "symbol": "CITICHEM",
        "name": "Citichem India",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 70.0 for 0.00% gains",
        "min_price": 70,
        "max_price": 70,
        "issue_price": 70,
        "listing_gains": 0,
        "listing_price": 70,
        "bidding_start_date": "2024-12-27",
        "bidding_end_date": null,
        "listing_date": "2025-01-03",
        "lot_size": null,
        "document_url": "https://www.citichemindia.com/draftCitiChemIndia.pdf"
      },
      {
        "symbol": "ANYA",
        "name": "Anya Polytech",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 17.1 for 22.14% gains",
        "min_price": 13,
        "max_price": 14,
        "issue_price": 14,
        "listing_gains": 22.142857142857153,
        "listing_price": 17.1,
        "bidding_start_date": "2024-12-26",
        "bidding_end_date": null,
        "listing_date": "2025-01-02",
        "lot_size": null,
        "document_url": "https://www.apfl.in/investor/red-herring-prospectus"
      },
      {
        "symbol": "UNIMECH",
        "name": "Unimech Aerospace",
        "status": "listed",
        "is_sme": false,
        "additional_text": "Listed at 1460.0 for 85.99% gains",
        "min_price": 745,
        "max_price": 785,
        "issue_price": 785,
        "listing_gains": 85.98726114649682,
        "listing_price": 1460,
        "bidding_start_date": "2024-12-23",
        "bidding_end_date": null,
        "listing_date": "2024-12-31",
        "lot_size": null,
        "document_url": "https://unimechaerospace.com/wp-content/uploads/2024/12/Red-Herring-Prospectus-Unimech.pdf"
      },
      {
        "symbol": "CARRARO",
        "name": "Carraro India",
        "status": "listed",
        "is_sme": false,
        "additional_text": "Listed at 651.0 for 7.53% loss",
        "min_price": 668,
        "max_price": 704,
        "issue_price": 704,
        "listing_gains": -7.528409090909091,
        "listing_price": 651,
        "bidding_start_date": "2024-12-20",
        "bidding_end_date": null,
        "listing_date": "2024-12-30",
        "lot_size": null,
        "document_url": "https://www.axiscapital.co.in/wp-content/uploads/Carraro-India-Limited-RHP.pdf"
      },
      {
        "symbol": "SENORES",
        "name": "Senores Pharmaceuticals",
        "status": "listed",
        "is_sme": false,
        "additional_text": "Listed at 600.0 for 53.45% gains",
        "min_price": 372,
        "max_price": 391,
        "issue_price": 391,
        "listing_gains": 53.452685421994886,
        "listing_price": 600,
        "bidding_start_date": "2024-12-20",
        "bidding_end_date": null,
        "listing_date": "2024-12-30",
        "lot_size": null,
        "document_url": "https://senorespharma.com/wp-content/uploads/2024/12/Senores-Pharmaceuticals-Limited-RHP.pdf"
      },
      {
        "symbol": "VENTIVE",
        "name": "Ventive Hospitality",
        "status": "listed",
        "is_sme": false,
        "additional_text": "Listed at 716.0 for 11.35% gains",
        "min_price": 610,
        "max_price": 643,
        "issue_price": 643,
        "listing_gains": 11.35303265940902,
        "listing_price": 716,
        "bidding_start_date": "2024-12-20",
        "bidding_end_date": null,
        "listing_date": "2024-12-30",
        "lot_size": null,
        "document_url": "https://www.ventivehospitality.com/wp-content/uploads/2024/07/Project-Puma-RHP-Final-Filing.pdf"
      },
      {
        "symbol": "DAMCAPITAL",
        "name": "DAM Capital Advisor",
        "status": "listed",
        "is_sme": false,
        "additional_text": "Listed at 393.0 for 38.87% gains",
        "min_price": 269,
        "max_price": 283,
        "issue_price": 283,
        "listing_gains": 38.869257950530034,
        "listing_price": 393,
        "bidding_start_date": "2024-12-19",
        "bidding_end_date": null,
        "listing_date": "2024-12-27",
        "lot_size": null,
        "document_url": "https://www.damcapital.in/files/investorrelation/638610542652190066_DCAL.pdf"
      },
      {
        "symbol": "SANATHAN",
        "name": "Sanathan Textiles",
        "status": "listed",
        "is_sme": false,
        "additional_text": "Listed at 422.3 for 31.56% gains",
        "min_price": 305,
        "max_price": 321,
        "issue_price": 321,
        "listing_gains": 31.5576323987539,
        "listing_price": 422.3,
        "bidding_start_date": "2024-12-19",
        "bidding_end_date": null,
        "listing_date": "2024-12-27",
        "lot_size": null,
        "document_url": "https://www.sebi.gov.in/filings/public-issues/dec-2024/sanathan-textiles-limited-rhp_89960.html"
      },
      {
        "symbol": "NMSTEEL",
        "name": "Newmalayalam Steel",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 90.0 for 0.00% gains",
        "min_price": 85,
        "max_price": 90,
        "issue_price": 90,
        "listing_gains": 0,
        "listing_price": 90,
        "bidding_start_date": "2024-12-19",
        "bidding_end_date": null,
        "listing_date": "2024-12-27",
        "lot_size": null,
        "document_url": "https://demacsteel.com/wp-content/uploads/2024/12/NewMalayalam-Steel-Limited-RHP.pdf"
      },
      {
        "symbol": "MAMATA",
        "name": "Mamata Machinery",
        "status": "listed",
        "is_sme": false,
        "additional_text": "Listed at 600.0 for 146.91% gains",
        "min_price": 230,
        "max_price": 243,
        "issue_price": 243,
        "listing_gains": 146.9135802469136,
        "listing_price": 600,
        "bidding_start_date": "2024-12-19",
        "bidding_end_date": null,
        "listing_date": "2024-12-27",
        "lot_size": null,
        "document_url": "https://www.mamata.com/investors/Mamata_Machinery_Limited_RHP.pdf"
      },
      {
        "symbol": "CEWATER",
        "name": "Concord Enviro Systems",
        "status": "listed",
        "is_sme": false,
        "additional_text": "Listed at 826.0 for 17.83% gains",
        "min_price": 665,
        "max_price": 701,
        "issue_price": 701,
        "listing_gains": 17.83166904422254,
        "listing_price": 826,
        "bidding_start_date": "2024-12-19",
        "bidding_end_date": null,
        "listing_date": "2024-12-27",
        "lot_size": null,
        "document_url": "https://www.sebi.gov.in/filings/public-issues/dec-2024/concord-enviro-systems-limited-rhp_89957.html"
      },
      {
        "symbol": "TRANSRAILL",
        "name": "Transrail Lighting",
        "status": "listed",
        "is_sme": false,
        "additional_text": "Listed at 590.0 for 36.57% gains",
        "min_price": 410,
        "max_price": 432,
        "issue_price": 432,
        "listing_gains": 36.574074074074076,
        "listing_price": 590,
        "bidding_start_date": "2024-12-19",
        "bidding_end_date": null,
        "listing_date": "2024-12-27",
        "lot_size": null,
        "document_url": "https://transrail.in/images/files/RHP/Red-Herring-Prospectus-(RHP).pdf"
      },
      {
        "symbol": "IDENTICAL",
        "name": "Identical Brains Studios",
        "status": "listed",
        "is_sme": true,
        "additional_text": "Listed at 95.0 for 75.93% gains",
        "min_price": 51,
        "max_price": 54,
        "issue_price": 54,
        "listing_gains": 75.92592592592592,
        "listing_price": 95,
        "bidding_start_date": "2024-12-18",
        "bidding_end_date": null,
        "listing_date": "2024-12-26",
        "lot_size": null,
        "document_url": "https://identicalbrains.com/reports/drhp-identical-brains-studios-limited.pdf"
      }
    ],
    "active": [
      {
        "symbol": "LKMEHTA",
        "name": "LK Mehta Polymers Limited",
        "status": "active",
        "is_sme": true,
        "additional_text": "IPO closes today at 4:50 PM",
        "min_price": 71,
        "max_price": 71,
        "issue_price": null,
        "listing_gains": null,
        "listing_price": null,
        "bidding_start_date": "2025-02-13",
        "bidding_end_date": "2025-02-17",
        "listing_date": null,
        "lot_size": 1600,
        "document_url": null
      },
      {
        "symbol": "SHANMUGA",
        "name": "Shanmuga Hospital Limited",
        "status": "active",
        "is_sme": true,
        "additional_text": "IPO closes today at 4:50 PM",
        "min_price": 54,
        "max_price": 54,
        "issue_price": null,
        "listing_gains": null,
        "listing_price": null,
        "bidding_start_date": "2025-02-13",
        "bidding_end_date": "2025-02-17",
        "listing_date": null,
        "lot_size": 2000,
        "document_url": null
      },
      {
        "symbol": "QPOWER",
        "name": "Quality Power Electrical Equipments Limited",
        "status": "active",
        "is_sme": false,
        "additional_text": "Closes on 18 Feb at 4:50 PM",
        "min_price": 401,
        "max_price": 425,
        "issue_price": null,
        "listing_gains": null,
        "listing_price": null,
        "bidding_start_date": "2025-02-14",
        "bidding_end_date": "2025-02-18",
        "listing_date": null,
        "lot_size": 26,
        "document_url": null
      },
      {
        "symbol": "ROYALARC",
        "name": "Royalarc Electrodes Limited",
        "status": "active",
        "is_sme": true,
        "additional_text": "Closes on 18 Feb at 4:50 PM",
        "min_price": 114,
        "max_price": 120,
        "issue_price": null,
        "listing_gains": null,
        "listing_price": null,
        "bidding_start_date": "2025-02-14",
        "bidding_end_date": "2025-02-18",
        "listing_date": null,
        "lot_size": 1200,
        "document_url": null
      },
      {
        "symbol": "TEJASCARGO",
        "name": "Tejas Cargo Limited",
        "status": "active",
        "is_sme": true,
        "additional_text": "Closes on 18 Feb at 4:50 PM",
        "min_price": 160,
        "max_price": 168,
        "issue_price": null,
        "listing_gains": null,
        "listing_price": null,
        "bidding_start_date": "2025-02-14",
        "bidding_end_date": "2025-02-18",
        "listing_date": null,
        "lot_size": 800,
        "document_url": null
      }
    ],
    "closed": [
      {
        "symbol": "PSRAJ",
        "name": "PS Raj Steels Limited",
        "status": "closed",
        "is_sme": true,
        "additional_text": "Listing on 19 Feb at 10 AM",
        "min_price": 132,
        "max_price": 140,
        "issue_price": null,
        "listing_gains": null,
        "listing_price": null,
        "bidding_start_date": "2025-02-12",
        "bidding_end_date": null,
        "listing_date": "2025-02-19",
        "lot_size": null,
        "document_url": "https://pssrgroup.com/wp-content/uploads/2025/02/Red-Herring-Prospectus__PSRAJSTEELSLTD.pdf"
      },
      {
        "symbol": "HEXT",
        "name": "Hexaware Technologies Limited",
        "status": "closed",
        "is_sme": false,
        "additional_text": "Listing on 19 Feb at 10 AM",
        "min_price": 674,
        "max_price": 708,
        "issue_price": null,
        "listing_gains": null,
        "listing_price": null,
        "bidding_start_date": "2025-02-12",
        "bidding_end_date": null,
        "listing_date": "2025-02-19",
        "lot_size": null,
        "document_url": "https://hexaware.com/wp-content/uploads/2025/02/Red-Herring-Prospectus.pdf"
      },
      {
        "symbol": "VOLERCAR",
        "name": "Voler Car Limited",
        "status": "closed",
        "is_sme": true,
        "additional_text": "Listing on 19 Feb at 10 AM",
        "min_price": 85,
        "max_price": 90,
        "issue_price": null,
        "listing_gains": null,
        "listing_price": null,
        "bidding_start_date": "2025-02-12",
        "bidding_end_date": null,
        "listing_date": "2025-02-19",
        "lot_size": null,
        "document_url": "https://volercars.com/wp-content/uploads/2025/02/RHP_Voler-Car-Limited.pdf"
      },
      {
        "symbol": "MAXVOLT",
        "name": "Maxvolt Energy Industries Limited",
        "status": "closed",
        "is_sme": true,
        "additional_text": "Listing on 19 Feb at 10 AM",
        "min_price": 171,
        "max_price": 180,
        "issue_price": null,
        "listing_gains": null,
        "listing_price": null,
        "bidding_start_date": "2025-02-12",
        "bidding_end_date": null,
        "listing_date": "2025-02-19",
        "lot_size": null,
        "document_url": "https://shcapl.com/wp-content/uploads/2025/02/Maxvolt_RHP.pdf"
      }
    ]
  
};